// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Obss.CRM.Infrastructure.Persistence;

#nullable disable

namespace Obss.CRM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260712180248_FixnewPendingChanges_CRM")]
    partial class FixnewPendingChanges_CRM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Obss.CRM.Domain.Entities.Agreement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgreementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("agreement_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_at");

                    b.Property<string>("SignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("signed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_agreements");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_agreements_customer_id");

                    b.ToTable("agreements", (string)null);
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsBilling")
                        .HasColumnType("boolean")
                        .HasColumnName("is_billing");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<bool>("IsTechnical")
                        .HasColumnType("boolean")
                        .HasColumnName("is_technical");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_contacts_customer_id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_contacts_email");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.CreditProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("RiskRating")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_rating");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("ScoreType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("score_type");

                    b.HasKey("Id")
                        .HasName("pk_customer_credit_profiles");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_credit_profiles_customer_id");

                    b.ToTable("customer_credit_profiles", (string)null);
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("credit_limit");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_type");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<string>("Href")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("href");

                    b.Property<Guid?>("IndividualId")
                        .HasColumnType("uuid")
                        .HasColumnName("individual_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("registration_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("status_reason");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_number");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("CustomerType")
                        .HasDatabaseName("ix_customers_customer_type");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("ix_customers_display_name");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_customers_email");

                    b.HasIndex("IndividualId")
                        .HasDatabaseName("ix_customers_individual_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_customers_organization_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_customers_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_customers_tenant_id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.CustomerNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.HasKey("Id")
                        .HasName("pk_customer_notes");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_customer_notes_category");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_notes_customer_id");

                    b.ToTable("customer_notes", (string)null);
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.CustomerSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("criteria");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customer_segments");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_customer_segments_name");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_customer_segments_priority");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_customer_segments_tenant_id");

                    b.ToTable("customer_segments", (string)null);
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.CustomerSegmentAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsAutoAssigned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto_assigned");

                    b.Property<Guid>("SegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("segment_id");

                    b.HasKey("Id")
                        .HasName("pk_customer_segment_assignments");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_segment_assignments_customer_id");

                    b.HasIndex("SegmentId")
                        .HasDatabaseName("ix_customer_segment_assignments_segment_id");

                    b.HasIndex("SegmentId", "CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_segment_assignments_segment_customer");

                    b.ToTable("customer_segment_assignments", (string)null);
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.IdentityDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("document_number");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("document_type");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<Guid>("IndividualId")
                        .HasColumnType("uuid")
                        .HasColumnName("individual_id");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<DateTime?>("IssuedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_date");

                    b.Property<string>("IssuingAuthority")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuing_authority");

                    b.Property<string>("IssuingCountry")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("issuing_country");

                    b.HasKey("Id")
                        .HasName("pk_individual_identity_documents");

                    b.HasIndex("IndividualId")
                        .HasDatabaseName("ix_individual_identity_documents_individual_id");

                    b.ToTable("individual_identity_documents", (string)null);
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.Individual", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kyc_status");

                    b.Property<DateTime?>("KycVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kyc_verified_at");

                    b.Property<string>("KycVerifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("kyc_verified_by");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("nationality");

                    b.Property<string>("RiskRating")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("risk_rating");

                    b.Property<string>("Salutation")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("salutation");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_individuals");

                    b.ToTable("individuals", (string)null);
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("company_type");

                    b.Property<string>("CountryOfRegistration")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("country_of_registration");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("industry");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kyc_status");

                    b.Property<DateTime?>("KycVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kyc_verified_at");

                    b.Property<string>("KycVerifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("kyc_verified_by");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("registration_number");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_number");

                    b.Property<string>("TradingName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trading_name");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EffectiveQuoteCompletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_quote_completion_date");

                    b.Property<DateTime?>("ExpectedFulfillmentStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_fulfillment_start_date");

                    b.Property<DateTime?>("ExpectedQuoteCompletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_quote_completion_date");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<DateTime>("QuoteDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quote_date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_quotes");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_quotes_customer_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_quotes_state");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_quotes_tenant_id");

                    b.ToTable("quotes", (string)null);
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.QuoteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("ProductOfferingId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_offering_id");

                    b.Property<string>("ProductOfferingName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_offering_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_quote_items");

                    b.HasIndex("QuoteId")
                        .HasDatabaseName("ix_quote_items_quote_id");

                    b.ToTable("quote_items", (string)null);
                });

            modelBuilder.Entity("Obss.SharedKernel.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<string>("HandlerName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("handler_name");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_inbox_messages_received_at");

                    b.HasIndex("EventId", "HandlerName")
                        .IsUnique()
                        .HasDatabaseName("ix_inbox_messages_event_id_handler_name");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Obss.SharedKernel.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_created_at");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.Contact", b =>
                {
                    b.HasOne("Obss.CRM.Domain.Entities.Customer", "Customer")
                        .WithMany("Contacts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contacts_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.CreditProfile", b =>
                {
                    b.HasOne("Obss.CRM.Domain.Entities.Customer", null)
                        .WithMany("CreditProfiles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_credit_profiles_customers_customer_id");

                    b.OwnsOne("Obss.SharedKernel.Domain.ValueObjects.TimePeriod", "ValidFor", b1 =>
                        {
                            b1.Property<Guid>("CreditProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("EndDateTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_until");

                            b1.Property<DateTime?>("StartDateTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_from");

                            b1.HasKey("CreditProfileId");

                            b1.ToTable("customer_credit_profiles");

                            b1.WithOwner()
                                .HasForeignKey("CreditProfileId")
                                .HasConstraintName("fk_customer_credit_profiles_customer_credit_profiles_id");
                        });

                    b.Navigation("ValidFor")
                        .IsRequired();
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Obss.CRM.Domain.Entities.Individual", "Individual")
                        .WithMany()
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_customers_individuals_individual_id");

                    b.HasOne("Obss.CRM.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_customers_organizations_organization_id");

                    b.OwnsOne("Obss.SharedKernel.Domain.ValueObjects.TimePeriod", "ValidFor", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("EndDateTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_until");

                            b1.Property<DateTime?>("StartDateTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_from");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId")
                                .HasConstraintName("fk_customers_customers_id");
                        });

                    b.OwnsMany("Obss.CRM.Domain.ValueObjects.AccountRef", "AccountRefs", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AccountType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("account_type");

                            b1.Property<Guid>("BillingAccountId")
                                .HasColumnType("uuid")
                                .HasColumnName("billing_account_id");

                            b1.Property<string>("Href")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("href");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("role");

                            b1.Property<Guid>("customer_id")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.HasKey("Id");

                            b1.HasIndex("customer_id")
                                .HasDatabaseName("ix_customer_account_refs_customer_id");

                            b1.ToTable("customer_account_refs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("customer_id")
                                .HasConstraintName("fk_customer_account_refs_customers_customer_id");
                        });

                    b.OwnsMany("Obss.CRM.Domain.ValueObjects.AgreementRef", "AgreementRefs", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("AgreementId")
                                .HasColumnType("uuid")
                                .HasColumnName("agreement_id");

                            b1.Property<string>("AgreementType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("agreement_type");

                            b1.Property<string>("Href")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("href");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("role");

                            b1.Property<Guid>("customer_id")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.HasKey("Id");

                            b1.HasIndex("customer_id")
                                .HasDatabaseName("ix_customer_agreement_refs_customer_id");

                            b1.ToTable("customer_agreement_refs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("customer_id")
                                .HasConstraintName("fk_customer_agreement_refs_customers_customer_id");
                        });

                    b.OwnsMany("Obss.CRM.Domain.ValueObjects.RelatedParty", "RelatedParties", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.Property<Guid>("ReferredId")
                                .HasColumnType("uuid")
                                .HasColumnName("referred_id");

                            b1.Property<string>("ReferredType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("referred_type");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("role");

                            b1.Property<Guid>("customer_id")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.HasKey("Id");

                            b1.HasIndex("customer_id")
                                .HasDatabaseName("ix_customer_related_parties_customer_id");

                            b1.ToTable("customer_related_parties", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("customer_id")
                                .HasConstraintName("fk_customer_related_parties_customers_customer_id");
                        });

                    b.OwnsMany("Obss.CRM.Domain.ValueObjects.CharValue", "Characteristics", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("key");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("value");

                            b1.Property<string>("ValueType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("value_type");

                            b1.Property<Guid>("customer_id")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.HasKey("Id")
                                .HasName("pk_customer_characteristics");

                            b1.HasIndex("customer_id")
                                .HasDatabaseName("ix_customer_characteristics_customer_id");

                            b1.ToTable("customer_characteristics", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("customer_id")
                                .HasConstraintName("fk_customer_characteristics_customers_customer_id");
                        });

                    b.OwnsMany("Obss.CRM.Domain.ValueObjects.ContactMedium", "ContactMedia", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<bool>("IsPreferred")
                                .HasColumnType("boolean")
                                .HasColumnName("is_preferred");

                            b1.Property<string>("MediumType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("medium_type");

                            b1.Property<DateTime?>("ValidFrom")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_from");

                            b1.Property<DateTime?>("ValidUntil")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_until");

                            b1.Property<Guid>("customer_id")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.HasKey("Id")
                                .HasName("pk_customer_contact_media");

                            b1.HasIndex("customer_id")
                                .HasDatabaseName("ix_customer_contact_media_customer_id");

                            b1.ToTable("customer_contact_media", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("customer_id")
                                .HasConstraintName("fk_customer_contact_media_customers_customer_id");

                            b1.OwnsMany("Obss.CRM.Domain.ValueObjects.ContactCharValue", "Characteristics", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Key")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("key");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("value");

                                    b2.Property<string>("ValueType")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("character varying(30)")
                                        .HasColumnName("value_type");

                                    b2.Property<int>("contact_medium_id")
                                        .HasColumnType("integer")
                                        .HasColumnName("contact_medium_id");

                                    b2.HasKey("Id")
                                        .HasName("pk_customer_contact_medium_characteristics");

                                    b2.HasIndex("contact_medium_id")
                                        .HasDatabaseName("ix_customer_contact_medium_characteristics_contact_medium_id");

                                    b2.ToTable("customer_contact_medium_characteristics", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("contact_medium_id")
                                        .HasConstraintName("fk_customer_contact_medium_characteristics_customer_contact_me");
                                });

                            b1.Navigation("Characteristics");
                        });

                    b.OwnsMany("Obss.CRM.Domain.ValueObjects.NotificationHub", "NotificationHubs", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("HubType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("hub_type");

                            b1.Property<string>("Identifier")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("identifier");

                            b1.Property<bool>("IsOptIn")
                                .HasColumnType("boolean")
                                .HasColumnName("is_opt_in");

                            b1.Property<DateTime?>("ValidFrom")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_from");

                            b1.Property<DateTime?>("ValidUntil")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_until");

                            b1.Property<Guid>("customer_id")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.HasKey("Id")
                                .HasName("pk_customer_notification_hubs");

                            b1.HasIndex("customer_id")
                                .HasDatabaseName("ix_customer_notification_hubs_customer_id");

                            b1.ToTable("customer_notification_hubs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("customer_id")
                                .HasConstraintName("fk_customer_notification_hubs_customers_customer_id");
                        });

                    b.OwnsMany("Obss.CRM.Domain.ValueObjects.PaymentMethodRef", "PaymentMethodRefs", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Href")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("href");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.Property<Guid>("PaymentMethodId")
                                .HasColumnType("uuid")
                                .HasColumnName("payment_method_id");

                            b1.Property<Guid>("customer_id")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.HasKey("Id")
                                .HasName("pk_customer_payment_method_refs");

                            b1.HasIndex("customer_id")
                                .HasDatabaseName("ix_customer_payment_method_refs_customer_id");

                            b1.ToTable("customer_payment_method_refs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("customer_id")
                                .HasConstraintName("fk_customer_payment_method_refs_customers_customer_id");
                        });

                    b.Navigation("AccountRefs");

                    b.Navigation("AgreementRefs");

                    b.Navigation("Characteristics");

                    b.Navigation("ContactMedia");

                    b.Navigation("Individual");

                    b.Navigation("NotificationHubs");

                    b.Navigation("Organization");

                    b.Navigation("PaymentMethodRefs");

                    b.Navigation("RelatedParties");

                    b.Navigation("ValidFor");
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.CustomerNote", b =>
                {
                    b.HasOne("Obss.CRM.Domain.Entities.Customer", "Customer")
                        .WithMany("Notes")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_notes_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.CustomerSegmentAssignment", b =>
                {
                    b.HasOne("Obss.CRM.Domain.Entities.CustomerSegment", "Segment")
                        .WithMany("Assignments")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_segment_assignments_customer_segments_segment_id");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.IdentityDocument", b =>
                {
                    b.HasOne("Obss.CRM.Domain.Entities.Individual", null)
                        .WithMany("Documents")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_individual_identity_documents_individuals_individual_id");
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.Quote", b =>
                {
                    b.OwnsMany("Obss.CRM.Domain.ValueObjects.AgreementRef", "AgreementRefs", b1 =>
                        {
                            b1.Property<Guid>("QuoteId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<Guid>("AgreementId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AgreementType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Href")
                                .HasColumnType("text");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("QuoteId", "__synthesizedOrdinal");

                            b1.ToTable("quotes");

                            b1.ToJson("agreement_refs");

                            b1.WithOwner()
                                .HasForeignKey("QuoteId")
                                .HasConstraintName("fk_quotes_quotes_quote_id");
                        });

                    b.OwnsMany("Obss.CRM.Domain.ValueObjects.AccountRef", "BillingAccountRefs", b1 =>
                        {
                            b1.Property<Guid>("QuoteId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("AccountType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("BillingAccountId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Href")
                                .HasColumnType("text");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("QuoteId", "__synthesizedOrdinal");

                            b1.ToTable("quotes");

                            b1.ToJson("billing_account_refs");

                            b1.WithOwner()
                                .HasForeignKey("QuoteId")
                                .HasConstraintName("fk_quotes_quotes_quote_id");
                        });

                    b.OwnsMany("Obss.CRM.Domain.ValueObjects.Note", "Notes", b1 =>
                        {
                            b1.Property<Guid>("QuoteId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Author")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("QuoteId", "__synthesizedOrdinal");

                            b1.ToTable("quotes");

                            b1.ToJson("notes");

                            b1.WithOwner()
                                .HasForeignKey("QuoteId")
                                .HasConstraintName("fk_quotes_quotes_quote_id");
                        });

                    b.OwnsMany("Obss.CRM.Domain.ValueObjects.QuotePrice", "QuotePrices", b1 =>
                        {
                            b1.Property<Guid>("QuoteId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("DutyFreeAmount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("PriceType")
                                .HasColumnType("integer");

                            b1.Property<int?>("RecurringPeriod")
                                .HasColumnType("integer");

                            b1.Property<string>("RecurringPeriodUnit")
                                .HasColumnType("text");

                            b1.Property<decimal>("TaxIncludedAmount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("TaxRate")
                                .HasColumnType("numeric");

                            b1.Property<string>("UnitOfMeasure")
                                .HasColumnType("text");

                            b1.HasKey("QuoteId", "__synthesizedOrdinal");

                            b1.ToTable("quotes");

                            b1.ToJson("quote_prices");

                            b1.WithOwner()
                                .HasForeignKey("QuoteId")
                                .HasConstraintName("fk_quotes_quotes_quote_id");
                        });

                    b.OwnsMany("Obss.CRM.Domain.ValueObjects.RelatedParty", "RelatedParties", b1 =>
                        {
                            b1.Property<Guid>("QuoteId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("ReferredId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ReferredType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("QuoteId", "__synthesizedOrdinal");

                            b1.ToTable("quotes");

                            b1.ToJson("related_parties");

                            b1.WithOwner()
                                .HasForeignKey("QuoteId")
                                .HasConstraintName("fk_quotes_quotes_quote_id");
                        });

                    b.OwnsMany("Obss.CRM.Domain.ValueObjects.QuoteAuthorization", "Authorizations", b1 =>
                        {
                            b1.Property<Guid>("QuoteId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("ApproverName")
                                .HasColumnType("text");

                            b1.Property<string>("ApproverRole")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("GivenDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("RequestedDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("State")
                                .HasColumnType("integer");

                            b1.HasKey("QuoteId", "__synthesizedOrdinal")
                                .HasName("pk_quotes");

                            b1.ToTable("quotes");

                            b1.ToJson("quote_authorizations");

                            b1.WithOwner()
                                .HasForeignKey("QuoteId")
                                .HasConstraintName("fk_quotes_quotes_quote_id");
                        });

                    b.Navigation("AgreementRefs");

                    b.Navigation("Authorizations");

                    b.Navigation("BillingAccountRefs");

                    b.Navigation("Notes");

                    b.Navigation("QuotePrices");

                    b.Navigation("RelatedParties");
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.QuoteItem", b =>
                {
                    b.HasOne("Obss.CRM.Domain.Entities.Quote", null)
                        .WithMany("Items")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_quote_items_quotes_quote_id");

                    b.OwnsMany("Obss.CRM.Domain.ValueObjects.Note", "Notes", b1 =>
                        {
                            b1.Property<Guid>("QuoteItemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Author")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("QuoteItemId", "__synthesizedOrdinal")
                                .HasName("pk_quote_items");

                            b1.ToTable("quote_items");

                            b1.ToJson("notes");

                            b1.WithOwner()
                                .HasForeignKey("QuoteItemId")
                                .HasConstraintName("fk_quote_items_quote_items_quote_item_id");
                        });

                    b.OwnsMany("Obss.CRM.Domain.ValueObjects.QuotePrice", "Prices", b1 =>
                        {
                            b1.Property<Guid>("QuoteItemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("DutyFreeAmount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("PriceType")
                                .HasColumnType("integer");

                            b1.Property<int?>("RecurringPeriod")
                                .HasColumnType("integer");

                            b1.Property<string>("RecurringPeriodUnit")
                                .HasColumnType("text");

                            b1.Property<decimal>("TaxIncludedAmount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("TaxRate")
                                .HasColumnType("numeric");

                            b1.Property<string>("UnitOfMeasure")
                                .HasColumnType("text");

                            b1.HasKey("QuoteItemId", "__synthesizedOrdinal")
                                .HasName("pk_quote_items");

                            b1.ToTable("quote_items");

                            b1.ToJson("prices");

                            b1.WithOwner()
                                .HasForeignKey("QuoteItemId")
                                .HasConstraintName("fk_quote_items_quote_items_quote_item_id");
                        });

                    b.OwnsMany("Obss.CRM.Domain.ValueObjects.QuoteItemRelationship", "ItemRelationships", b1 =>
                        {
                            b1.Property<Guid>("QuoteItemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("RelatedItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("QuoteItemId", "__synthesizedOrdinal")
                                .HasName("pk_quote_items");

                            b1.ToTable("quote_items");

                            b1.ToJson("item_relationships");

                            b1.WithOwner()
                                .HasForeignKey("QuoteItemId")
                                .HasConstraintName("fk_quote_items_quote_items_quote_item_id");
                        });

                    b.Navigation("ItemRelationships");

                    b.Navigation("Notes");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("CreditProfiles");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.CustomerSegment", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.Individual", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Obss.CRM.Domain.Entities.Quote", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
