// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Obss.ServiceInventory.Infrastructure.Persistence;

#nullable disable

namespace Obss.ServiceInventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    [Migration("20260621165702_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Obss.ServiceInventory.Domain.Entities.ResourceDiscoveryJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Configuration")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("DiscoveryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("discovery_type");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<int>("ResourcesFound")
                        .HasColumnType("integer")
                        .HasColumnName("resources_found");

                    b.Property<int>("ResourcesMatched")
                        .HasColumnType("integer")
                        .HasColumnName("resources_matched");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_resource_discovery_jobs");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_resource_discovery_jobs_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_resource_discovery_jobs_tenant_id");

                    b.ToTable("resource_discovery_jobs", (string)null);
                });

            modelBuilder.Entity("Obss.ServiceInventory.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activation_date");

                    b.Property<string>("Configuration")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DecommissionedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decommissioned_at");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<string>("ServiceIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service_identifier");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("service_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_services_customer_id");

                    b.HasIndex("ServiceIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_services_service_identifier");

                    b.HasIndex("ServiceType")
                        .HasDatabaseName("ix_services_service_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_services_status");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_services_subscription_id");

                    b.HasIndex("CustomerId", "Status")
                        .HasDatabaseName("ix_services_customer_id_status");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("Obss.ServiceInventory.Domain.Entities.ServiceResource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AllocatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("allocated_at");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<string>("ResourceIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resource_identifier");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resource_type");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_service_resources");

                    b.HasIndex("ResourceIdentifier")
                        .HasDatabaseName("ix_service_resources_resource_identifier");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_resources_service_id");

                    b.ToTable("service_resources", (string)null);
                });

            modelBuilder.Entity("Obss.ServiceInventory.Domain.Entities.ServiceTopology", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("TopologyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("topology_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_service_topologies");

                    b.HasIndex("ServiceId")
                        .IsUnique()
                        .HasDatabaseName("ix_service_topologies_service_id");

                    b.ToTable("service_topologies", (string)null);
                });

            modelBuilder.Entity("Obss.ServiceInventory.Domain.Entities.TopologyLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Attributes")
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("direction");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("link_type");

                    b.Property<Guid>("ServiceTopologyId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_topology_id");

                    b.Property<Guid>("SourceServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_service_id");

                    b.Property<Guid>("TargetServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_service_id");

                    b.HasKey("Id")
                        .HasName("pk_topology_links");

                    b.HasIndex("ServiceTopologyId")
                        .HasDatabaseName("ix_topology_links_service_topology_id");

                    b.HasIndex("SourceServiceId")
                        .HasDatabaseName("ix_topology_links_source_service_id");

                    b.HasIndex("TargetServiceId")
                        .HasDatabaseName("ix_topology_links_target_service_id");

                    b.ToTable("topology_links", (string)null);
                });

            modelBuilder.Entity("Obss.SharedKernel.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_created_at");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Obss.ServiceInventory.Domain.Entities.ServiceResource", b =>
                {
                    b.HasOne("Obss.ServiceInventory.Domain.Entities.Service", null)
                        .WithMany("Resources")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_resources_services_service_id");
                });

            modelBuilder.Entity("Obss.ServiceInventory.Domain.Entities.TopologyLink", b =>
                {
                    b.HasOne("Obss.ServiceInventory.Domain.Entities.ServiceTopology", null)
                        .WithMany("Links")
                        .HasForeignKey("ServiceTopologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topology_links_service_topologies_service_topology_id");
                });

            modelBuilder.Entity("Obss.ServiceInventory.Domain.Entities.Service", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Obss.ServiceInventory.Domain.Entities.ServiceTopology", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
