// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Obss.Billing.Infrastructure.Persistence;

#nullable disable

namespace Obss.Billing.Infrastructure.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Obss.Billing.Domain.Entities.AccountBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AtBaseType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("at_base_type");

                    b.Property<string>("AtSchemaLocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("at_schema_location");

                    b.Property<string>("AtType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("at_type");

                    b.Property<decimal>("AvailableCredit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("available_credit");

                    b.Property<DateTime>("BalanceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("balance_date");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("current_balance");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<decimal>("OutstandingBalance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("outstanding_balance");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_account_balances");

                    b.HasIndex("BalanceDate")
                        .HasDatabaseName("ix_account_balances_balance_date");

                    b.HasIndex("BillingAccountId")
                        .HasDatabaseName("ix_account_balances_billing_account_id");

                    b.ToTable("account_balances", (string)null);
                });

            modelBuilder.Entity("Obss.Billing.Domain.Entities.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AtBaseType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("at_base_type");

                    b.Property<string>("AtSchemaLocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("at_schema_location");

                    b.Property<string>("AtType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("at_type");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("billing_period");

                    b.Property<DateTime>("BillingPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("billing_period_end");

                    b.Property<DateTime>("BillingPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("billing_period_start");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<decimal>("DiscountTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_total");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("grand_total");

                    b.Property<string>("Href")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("href");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sub_total");

                    b.Property<decimal>("TaxTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_total");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_bills");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_bills_customer_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_bills_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bills_tenant_id");

                    b.HasIndex("CustomerId", "Status")
                        .HasDatabaseName("ix_bills_customer_id_status");

                    b.ToTable("bills", (string)null);
                });

            modelBuilder.Entity("Obss.Billing.Domain.Entities.BillLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<DateTime>("LineDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("line_date");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("line_type");

                    b.Property<Guid?>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("tax_rate");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_bill_lines");

                    b.HasIndex("BillId")
                        .HasDatabaseName("ix_bill_lines_bill_id");

                    b.ToTable("bill_lines", (string)null);
                });

            modelBuilder.Entity("Obss.Billing.Domain.Entities.BillingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_type");

                    b.Property<string>("AtBaseType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("at_base_type");

                    b.Property<string>("AtSchemaLocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("at_schema_location");

                    b.Property<string>("AtType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("at_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("credit_limit");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<string>("Href")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("href");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PaymentMethodId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payment_method_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_billing_accounts");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_billing_accounts_customer_id");

                    b.ToTable("billing_accounts", (string)null);
                });

            modelBuilder.Entity("Obss.Billing.Domain.Entities.BillingCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("billing_period");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<DateTime>("LastBillingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_billing_date");

                    b.Property<DateTime>("NextBillingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_billing_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_billing_cycles");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_billing_cycles_customer_id");

                    b.HasIndex("NextBillingDate")
                        .HasDatabaseName("ix_billing_cycles_next_billing_date");

                    b.ToTable("billing_cycles", (string)null);
                });

            modelBuilder.Entity("Obss.Billing.Domain.Entities.BillingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_type");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TotalErrors")
                        .HasColumnType("integer")
                        .HasColumnName("total_errors");

                    b.Property<int>("TotalProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("total_processed");

                    b.HasKey("Id")
                        .HasName("pk_billing_jobs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_billing_jobs_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_billing_jobs_status");

                    b.ToTable("billing_jobs", (string)null);
                });

            modelBuilder.Entity("Obss.Billing.Domain.Entities.TaxExemption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("approved_by");

                    b.Property<Guid?>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("ExemptionCertificate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("exemption_certificate");

                    b.Property<decimal>("ExemptionRate")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("exemption_rate");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<Guid>("TaxRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("tax_rule_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_tax_exemptions");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_tax_exemptions_customer_id");

                    b.HasIndex("CustomerId", "TaxRuleId")
                        .HasDatabaseName("ix_tax_exemptions_customer_tax_rule");

                    b.ToTable("tax_exemptions", (string)null);
                });

            modelBuilder.Entity("Obss.Billing.Domain.Entities.TaxRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("YE")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCompound")
                        .HasColumnType("boolean")
                        .HasColumnName("is_compound");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<string>("TaxCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tax_category");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("tax_rate");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_type");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tax_rules");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_tax_rules_is_active");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tax_rules_tenant_id");

                    b.HasIndex("TaxCategory", "Country")
                        .HasDatabaseName("ix_tax_rules_category_country");

                    b.ToTable("tax_rules", (string)null);
                });

            modelBuilder.Entity("Obss.SharedKernel.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<string>("HandlerName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("handler_name");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_inbox_messages_received_at");

                    b.HasIndex("EventId", "HandlerName")
                        .IsUnique()
                        .HasDatabaseName("ix_inbox_messages_event_id_handler_name");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Obss.SharedKernel.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsDeadLettered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dead_lettered");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LockExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lock_expires_at");

                    b.Property<Guid?>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_created_at");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.HasIndex("ProcessedAt", "NextAttemptAt", "IsDeadLettered")
                        .HasDatabaseName("ix_outbox_messages_pending");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Obss.Billing.Domain.Entities.AccountBalance", b =>
                {
                    b.OwnsMany("Obss.Billing.Domain.Entities.BalanceTransaction", "Transactions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("amount");

                            b1.Property<Guid>("BalanceId")
                                .HasColumnType("uuid")
                                .HasColumnName("balance_id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<string>("ReferenceId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("reference_id");

                            b1.Property<string>("ReferenceType")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("reference_type");

                            b1.Property<DateTime>("TransactionDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("transaction_date");

                            b1.Property<string>("TransactionType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("transaction_type");

                            b1.Property<Guid>("balance_id")
                                .HasColumnType("uuid")
                                .HasColumnName("balance_id");

                            b1.HasKey("Id")
                                .HasName("pk_balance_transactions");

                            b1.HasIndex("balance_id")
                                .HasDatabaseName("ix_balance_transactions_balance_id");

                            b1.ToTable("balance_transactions", null, t =>
                                {
                                    t.Property("balance_id")
                                        .HasColumnName("balance_id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("balance_id")
                                .HasConstraintName("fk_balance_transactions_account_balances_balance_id");
                        });

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Obss.Billing.Domain.Entities.Bill", b =>
                {
                    b.OwnsMany("Obss.Billing.Domain.Entities.RelatedParty", "RelatedParties", b1 =>
                        {
                            b1.Property<Guid>("bill_id")
                                .HasColumnType("uuid")
                                .HasColumnName("bill_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("PartyId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("party_id");

                            b1.Property<string>("PartyName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("party_name");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("role");

                            b1.HasKey("bill_id", "Id")
                                .HasName("pk_bill_related_parties");

                            b1.ToTable("bill_related_parties", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("bill_id")
                                .HasConstraintName("fk_bill_related_parties_bills_bill_id");
                        });

                    b.Navigation("RelatedParties");
                });

            modelBuilder.Entity("Obss.Billing.Domain.Entities.BillLine", b =>
                {
                    b.HasOne("Obss.Billing.Domain.Entities.Bill", null)
                        .WithMany("Lines")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bill_lines_bills_bill_id");
                });

            modelBuilder.Entity("Obss.Billing.Domain.Entities.BillingAccount", b =>
                {
                    b.OwnsOne("Obss.Billing.Domain.ValueObjects.AccountHolder", "AccountHolder", b1 =>
                        {
                            b1.Property<Guid>("BillingAccountId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("ContactId")
                                .HasColumnType("uuid")
                                .HasColumnName("account_holder_contact_id");

                            b1.Property<string>("Email")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("account_holder_email");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("account_holder_name");

                            b1.Property<string>("Phone")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("account_holder_phone");

                            b1.HasKey("BillingAccountId");

                            b1.ToTable("billing_accounts");

                            b1.WithOwner()
                                .HasForeignKey("BillingAccountId")
                                .HasConstraintName("fk_billing_accounts_billing_accounts_id");
                        });

                    b.OwnsMany("Obss.Billing.Domain.Entities.BillPresentationMedia", "BillPresentationMedia", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("EmailAddress")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email_address");

                            b1.Property<bool>("IsPreferred")
                                .HasColumnType("boolean")
                                .HasColumnName("is_preferred");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("language");

                            b1.Property<string>("MediaType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("media_type");

                            b1.Property<string>("PaperFormat")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("paper_format");

                            b1.Property<DateTime?>("ValidFrom")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_from");

                            b1.Property<DateTime?>("ValidUntil")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_until");

                            b1.Property<Guid>("billing_account_id")
                                .HasColumnType("uuid")
                                .HasColumnName("billing_account_id");

                            b1.HasKey("Id")
                                .HasName("pk_billing_account_presentation_media");

                            b1.HasIndex("billing_account_id")
                                .HasDatabaseName("ix_billing_account_presentation_media_billing_account_id");

                            b1.ToTable("billing_account_presentation_media", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("billing_account_id")
                                .HasConstraintName("fk_billing_account_presentation_media_billing_accounts_billing");
                        });

                    b.OwnsMany("Obss.Billing.Domain.Entities.RelatedParty", "RelatedParties", b1 =>
                        {
                            b1.Property<Guid>("billing_account_id")
                                .HasColumnType("uuid")
                                .HasColumnName("billing_account_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("PartyId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("party_id");

                            b1.Property<string>("PartyName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("party_name");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("role");

                            b1.HasKey("billing_account_id", "Id")
                                .HasName("pk_billing_account_related_parties");

                            b1.ToTable("billing_account_related_parties", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("billing_account_id")
                                .HasConstraintName("fk_billing_account_related_parties_billing_accounts_billing_ac");
                        });

                    b.Navigation("AccountHolder");

                    b.Navigation("BillPresentationMedia");

                    b.Navigation("RelatedParties");
                });

            modelBuilder.Entity("Obss.Billing.Domain.Entities.Bill", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
