// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Obss.ProductCatalog.Infrastructure.Persistence;

#nullable disable

namespace Obss.ProductCatalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260621170454_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Obss.ProductCatalog.Domain.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_categories_parent_category_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_categories_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_categories_tenant_id_name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Obss.ProductCatalog.Domain.Domain.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingPeriod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("billing_period");

                    b.Property<int?>("ContractDurationMonths")
                        .HasColumnType("integer")
                        .HasColumnName("contract_duration_months");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsContract")
                        .HasColumnType("boolean")
                        .HasColumnName("is_contract");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OfferType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("offer_type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<bool>("TaxInclusive")
                        .HasColumnType("boolean")
                        .HasColumnName("tax_inclusive");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_offers");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_offers_is_active");

                    b.HasIndex("OfferType")
                        .HasDatabaseName("ix_offers_offer_type");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_offers_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_offers_tenant_id_name");

                    b.ToTable("offers", (string)null);
                });

            modelBuilder.Entity("Obss.ProductCatalog.Domain.Domain.Entities.OfferDiscount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int?>("DiscountPeriodMonths")
                        .HasColumnType("integer")
                        .HasColumnName("discount_period_months");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_value");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_offer_discounts");

                    b.HasIndex("OfferId")
                        .HasDatabaseName("ix_offer_discounts_offer_id");

                    b.ToTable("offer_discounts", (string)null);
                });

            modelBuilder.Entity("Obss.ProductCatalog.Domain.Domain.Entities.OfferPricing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("max_quantity");

                    b.Property<int?>("MinQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("min_quantity");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<decimal>("OneTimePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("one_time_price");

                    b.Property<string>("PricingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pricing_type");

                    b.Property<decimal>("RecurringPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("recurring_price");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit_of_measure");

                    b.Property<decimal>("UsagePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("usage_price");

                    b.HasKey("Id")
                        .HasName("pk_offer_pricings");

                    b.HasIndex("OfferId")
                        .HasDatabaseName("ix_offer_pricings_offer_id");

                    b.ToTable("offer_pricings", (string)null);
                });

            modelBuilder.Entity("Obss.ProductCatalog.Domain.Domain.Entities.OptionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<decimal>("PriceAdjustment")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_adjustment");

                    b.Property<Guid>("ProductOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_option_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_option_values");

                    b.HasIndex("ProductOptionId")
                        .HasDatabaseName("ix_option_values_product_option_id");

                    b.ToTable("option_values", (string)null);
                });

            modelBuilder.Entity("Obss.ProductCatalog.Domain.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsShippable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shippable");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lifecycle_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("product_type");

                    b.Property<string>("TaxCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tax_category");

                    b.Property<bool>("Taxable")
                        .HasColumnType("boolean")
                        .HasColumnName("taxable");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("LifecycleStatus")
                        .HasDatabaseName("ix_products_lifecycle_status");

                    b.HasIndex("ProductType")
                        .HasDatabaseName("ix_products_product_type");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_products_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_products_tenant_id_name");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Obss.ProductCatalog.Domain.Domain.Entities.ProductConfigurationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Condition")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("condition");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rule_type");

                    b.Property<string>("TargetOption")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_option");

                    b.Property<Guid?>("TargetProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_configuration_rules");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_configuration_rules_product_id");

                    b.HasIndex("RuleType")
                        .HasDatabaseName("ix_product_configuration_rules_rule_type");

                    b.ToTable("product_configuration_rules", (string)null);
                });

            modelBuilder.Entity("Obss.ProductCatalog.Domain.Domain.Entities.ProductOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_offers");

                    b.HasIndex("OfferId")
                        .HasDatabaseName("ix_product_offers_offer_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_offers_product_id");

                    b.HasIndex("ProductId", "OfferId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_offers_product_offer");

                    b.ToTable("product_offers", (string)null);
                });

            modelBuilder.Entity("Obss.ProductCatalog.Domain.Domain.Entities.ProductOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsMultiSelect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_multi_select");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OptionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("option_type");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_product_options");

                    b.HasIndex("OptionType")
                        .HasDatabaseName("ix_product_options_option_type");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_options_product_id");

                    b.ToTable("product_options", (string)null);
                });

            modelBuilder.Entity("Obss.SharedKernel.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_created_at");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Obss.ProductCatalog.Domain.Domain.Entities.OfferDiscount", b =>
                {
                    b.HasOne("Obss.ProductCatalog.Domain.Domain.Entities.Offer", null)
                        .WithMany("Discounts")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_offer_discounts_offers_offer_id");
                });

            modelBuilder.Entity("Obss.ProductCatalog.Domain.Domain.Entities.OfferPricing", b =>
                {
                    b.HasOne("Obss.ProductCatalog.Domain.Domain.Entities.Offer", null)
                        .WithMany("OfferPricings")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_offer_pricings_offers_offer_id");
                });

            modelBuilder.Entity("Obss.ProductCatalog.Domain.Domain.Entities.OptionValue", b =>
                {
                    b.HasOne("Obss.ProductCatalog.Domain.Domain.Entities.ProductOption", null)
                        .WithMany("Values")
                        .HasForeignKey("ProductOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_option_values_product_options_product_option_id");
                });

            modelBuilder.Entity("Obss.ProductCatalog.Domain.Domain.Entities.Product", b =>
                {
                    b.OwnsMany("Obss.ProductCatalog.Domain.Domain.ValueObjects.ProductSpecification", "Specifications", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("boolean")
                                .HasColumnName("is_required");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("value");

                            b1.Property<Guid>("product_id")
                                .HasColumnType("uuid")
                                .HasColumnName("product_id");

                            b1.HasKey("Id")
                                .HasName("pk_product_specifications");

                            b1.HasIndex("product_id")
                                .HasDatabaseName("ix_product_specifications_product_id");

                            b1.ToTable("product_specifications", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("product_id")
                                .HasConstraintName("fk_product_specifications_products_product_id");
                        });

                    b.Navigation("Specifications");
                });

            modelBuilder.Entity("Obss.ProductCatalog.Domain.Domain.Entities.ProductOffer", b =>
                {
                    b.HasOne("Obss.ProductCatalog.Domain.Domain.Entities.Product", null)
                        .WithMany("ProductOffers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_offers_products_product_id");
                });

            modelBuilder.Entity("Obss.ProductCatalog.Domain.Domain.Entities.Offer", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("OfferPricings");
                });

            modelBuilder.Entity("Obss.ProductCatalog.Domain.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductOffers");
                });

            modelBuilder.Entity("Obss.ProductCatalog.Domain.Domain.Entities.ProductOption", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
