// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Obss.Provisioning.Infrastructure.Persistence;

#nullable disable

namespace Obss.Provisioning.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProvisioningDbContext))]
    [Migration("20260708184347_AddServiceOrderTables")]
    partial class AddServiceOrderTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ProvisioningJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("AtBaseType")
                        .HasColumnType("text")
                        .HasColumnName("at_base_type");

                    b.Property<string>("AtSchemaLocation")
                        .HasColumnType("text")
                        .HasColumnName("at_schema_location");

                    b.Property<string>("AtType")
                        .HasColumnType("text")
                        .HasColumnName("at_type");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Href")
                        .HasColumnType("text")
                        .HasColumnName("href");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<string>("Priority")
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("RelatedPartyId")
                        .HasColumnType("text")
                        .HasColumnName("related_party_id");

                    b.Property<string>("RelatedPartyName")
                        .HasColumnType("text")
                        .HasColumnName("related_party_name");

                    b.Property<string>("RelatedPartyRole")
                        .HasColumnType("text")
                        .HasColumnName("related_party_role");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("service_type");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WorkflowInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_instance_id");

                    b.HasKey("Id")
                        .HasName("pk_provisioning_jobs");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_provisioning_jobs_order_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_provisioning_jobs_service_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_provisioning_jobs_status");

                    b.ToTable("provisioning_jobs", (string)null);
                });

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ProvisioningTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<JsonDocument>("Configuration")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("ProvisioningJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("provisioning_job_id");

                    b.Property<JsonDocument>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer")
                        .HasColumnName("step_number");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_type");

                    b.HasKey("Id")
                        .HasName("pk_provisioning_tasks");

                    b.HasIndex("ProvisioningJobId")
                        .HasDatabaseName("ix_provisioning_tasks_provisioning_job_id");

                    b.ToTable("provisioning_tasks", (string)null);
                });

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ProvisioningTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ServiceSpecificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_specification_id");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("service_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_provisioning_templates");

                    b.HasIndex("TenantId", "ServiceType", "Action")
                        .HasDatabaseName("ix_provisioning_templates_tenant_service_action");

                    b.ToTable("provisioning_templates", (string)null);
                });

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ServiceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("CompletionMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("completion_message");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<string>("Href")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("href");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("RequestedCompletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_completion_date");

                    b.Property<DateTime?>("RequestedStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_start_date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("StatusChangeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_change_date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_service_orders");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("ix_service_orders_external_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_service_orders_state");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_service_orders_tenant_id");

                    b.ToTable("service_orders", (string)null);
                });

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ServiceOrderCharacteristic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<Guid?>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_service_order_characteristic");

                    b.HasIndex("ServiceOrderId")
                        .HasDatabaseName("ix_service_order_characteristic_service_order_id");

                    b.ToTable("service_order_characteristic", (string)null);
                });

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ServiceOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_date");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("RequestedCompletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_completion_date");

                    b.Property<DateTime?>("RequestedStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_start_date");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_service_order_items");

                    b.HasIndex("ServiceOrderId")
                        .HasDatabaseName("ix_service_order_items_service_order_id");

                    b.ToTable("service_order_items", (string)null);
                });

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ServiceOrderMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_service_order_milestone");

                    b.HasIndex("ServiceOrderId")
                        .HasDatabaseName("ix_service_order_milestone_service_order_id");

                    b.ToTable("service_order_milestone", (string)null);
                });

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ServiceOrderNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_service_order_note");

                    b.HasIndex("ServiceOrderId")
                        .HasDatabaseName("ix_service_order_note_service_order_id");

                    b.ToTable("service_order_note", (string)null);
                });

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ServiceOrderRelatedParty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PartyId")
                        .HasColumnType("text")
                        .HasColumnName("party_id");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid?>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.HasKey("Id")
                        .HasName("pk_service_order_related_party");

                    b.HasIndex("ServiceOrderId")
                        .HasDatabaseName("ix_service_order_related_party_service_order_id");

                    b.ToTable("service_order_related_party", (string)null);
                });

            modelBuilder.Entity("Obss.SharedKernel.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<string>("HandlerName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("handler_name");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_inbox_messages_received_at");

                    b.HasIndex("EventId", "HandlerName")
                        .IsUnique()
                        .HasDatabaseName("ix_inbox_messages_event_id_handler_name");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Obss.SharedKernel.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_created_at");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ProvisioningTask", b =>
                {
                    b.HasOne("Obss.Provisioning.Domain.Entities.ProvisioningJob", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ProvisioningJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provisioning_tasks_provisioning_jobs_provisioning_job_id");
                });

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ServiceOrder", b =>
                {
                    b.OwnsOne("Obss.Provisioning.Domain.Entities.CancelServiceOrder", "CancelRequest", b1 =>
                        {
                            b1.Property<Guid>("ServiceOrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("CompletedDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("cancel_completed_date");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("cancel_id");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("cancel_reason");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("cancel_state");

                            b1.HasKey("ServiceOrderId");

                            b1.ToTable("service_orders");

                            b1.WithOwner()
                                .HasForeignKey("ServiceOrderId")
                                .HasConstraintName("fk_service_orders_service_orders_id");
                        });

                    b.Navigation("CancelRequest");
                });

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ServiceOrderCharacteristic", b =>
                {
                    b.HasOne("Obss.Provisioning.Domain.Entities.ServiceOrder", null)
                        .WithMany("Characteristics")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_service_order_characteristic_service_orders_service_order_id");
                });

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ServiceOrderItem", b =>
                {
                    b.HasOne("Obss.Provisioning.Domain.Entities.ServiceOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_order_items_service_orders_service_order_id");
                });

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ServiceOrderMilestone", b =>
                {
                    b.HasOne("Obss.Provisioning.Domain.Entities.ServiceOrder", null)
                        .WithMany("Milestones")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_service_order_milestone_service_orders_service_order_id");
                });

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ServiceOrderNote", b =>
                {
                    b.HasOne("Obss.Provisioning.Domain.Entities.ServiceOrder", null)
                        .WithMany("Notes")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_service_order_note_service_orders_service_order_id");
                });

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ServiceOrderRelatedParty", b =>
                {
                    b.HasOne("Obss.Provisioning.Domain.Entities.ServiceOrder", null)
                        .WithMany("RelatedParties")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_service_order_related_party_service_orders_service_order_id");
                });

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ProvisioningJob", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Obss.Provisioning.Domain.Entities.ServiceOrder", b =>
                {
                    b.Navigation("Characteristics");

                    b.Navigation("Items");

                    b.Navigation("Milestones");

                    b.Navigation("Notes");

                    b.Navigation("RelatedParties");
                });
#pragma warning restore 612, 618
        }
    }
}
