// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Obss.NetworkInventory.Infrastructure.Persistence;

#nullable disable

namespace Obss.NetworkInventory.Infrastructure.Migrations
{
    [DbContext(typeof(NetworkDbContext))]
    [Migration("20260721205344_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.CapacityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AvailableCapacity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("available_capacity");

                    b.Property<string>("CapacityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("capacity_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("element_id");

                    b.Property<Guid?>("InterfaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("interface_id");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<decimal>("TotalCapacity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_capacity");

                    b.Property<decimal>("UsedCapacity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("used_capacity");

                    b.Property<decimal>("UtilizationPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("utilization_percent");

                    b.HasKey("Id")
                        .HasName("pk_capacity_records");

                    b.HasIndex("ElementId")
                        .HasDatabaseName("ix_capacity_records_element_id");

                    b.HasIndex("UtilizationPercent")
                        .HasDatabaseName("ix_capacity_records_utilization_percent");

                    b.ToTable("capacity_records", (string)null);
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.ConnectivityLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Bandwidth")
                        .HasColumnType("integer")
                        .HasColumnName("bandwidth");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("link_type");

                    b.Property<int>("MTU")
                        .HasColumnType("integer")
                        .HasColumnName("mtu");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Protocol")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("protocol");

                    b.Property<Guid>("SourceElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_element_id");

                    b.Property<Guid>("SourceInterfaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_interface_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_element_id");

                    b.Property<Guid>("TargetInterfaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_interface_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_connectivity_links");

                    b.HasIndex("SourceElementId")
                        .HasDatabaseName("ix_connectivity_links_source_element_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_connectivity_links_status");

                    b.HasIndex("TargetElementId")
                        .HasDatabaseName("ix_connectivity_links_target_element_id");

                    b.ToTable("connectivity_links", (string)null);
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.FiberCable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("FiberCount")
                        .HasColumnType("integer")
                        .HasColumnName("fiber_count");

                    b.Property<string>("FiberType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fiber_type");

                    b.Property<Guid>("FromElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_element_id");

                    b.Property<Guid>("FromInterfaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_interface_id");

                    b.Property<int>("Length")
                        .HasColumnType("integer")
                        .HasColumnName("length");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<int?>("SplicingPoints")
                        .HasColumnType("integer")
                        .HasColumnName("splicing_points");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("ToElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_element_id");

                    b.Property<Guid>("ToInterfaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_interface_id");

                    b.HasKey("Id")
                        .HasName("pk_fiber_cables");

                    b.HasIndex("FromElementId")
                        .HasDatabaseName("ix_fiber_cables_from_element_id");

                    b.HasIndex("ToElementId")
                        .HasDatabaseName("ix_fiber_cables_to_element_id");

                    b.ToTable("fiber_cables", (string)null);
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.MaintenanceWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("AffectedDeviceIds")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("affected_device_ids");

                    b.Property<string>("AffectedTechnology")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("affected_technology");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("approved_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<bool>("SuppressAlarms")
                        .HasColumnType("boolean")
                        .HasColumnName("suppress_alarms");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("TitleAr")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title_ar");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_windows");

                    b.HasIndex("AffectedTechnology")
                        .HasDatabaseName("ix_maintenance_windows_affected_technology");

                    b.HasIndex("EndTime")
                        .HasDatabaseName("ix_maintenance_windows_end_time");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("ix_maintenance_windows_start_time");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_maintenance_windows_status");

                    b.ToTable("maintenance_windows", (string)null);
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.NetworkElement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AtBaseType")
                        .HasColumnType("text")
                        .HasColumnName("at_base_type");

                    b.Property<string>("AtSchemaLocation")
                        .HasColumnType("text")
                        .HasColumnName("at_schema_location");

                    b.Property<string>("AtType")
                        .HasColumnType("text")
                        .HasColumnName("at_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("discriminator");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("element_type");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hostname");

                    b.Property<string>("Href")
                        .HasColumnType("text")
                        .HasColumnName("href");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsManaged")
                        .HasColumnType("boolean")
                        .HasColumnName("is_managed");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<string>("ManagementIP")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("management_ip");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("RelatedPartyId")
                        .HasColumnType("text")
                        .HasColumnName("related_party_id");

                    b.Property<string>("RelatedPartyName")
                        .HasColumnType("text")
                        .HasColumnName("related_party_name");

                    b.Property<string>("RelatedPartyRole")
                        .HasColumnType("text")
                        .HasColumnName("related_party_role");

                    b.Property<string>("ResourceCategory")
                        .HasColumnType("text")
                        .HasColumnName("resource_category");

                    b.Property<string>("SNMPCommunity")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("snmp_community");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<string>("SoftwareVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("software_version");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vendor");

                    b.HasKey("Id")
                        .HasName("pk_network_elements");

                    b.HasIndex("ElementType")
                        .HasDatabaseName("ix_network_elements_element_type");

                    b.HasIndex("Hostname")
                        .HasDatabaseName("ix_network_elements_hostname");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_network_elements_status");

                    b.HasIndex("TenantId", "Hostname")
                        .IsUnique()
                        .HasDatabaseName("ix_network_elements_tenant_id_hostname");

                    b.ToTable("network_elements", (string)null);

                    b.HasDiscriminator().HasValue("NetworkElement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.NetworkElementIpAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("address_type");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assigned_to");

                    b.Property<string>("Gateway")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("gateway");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reserved");

                    b.Property<Guid>("NetworkElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("network_element_id");

                    b.Property<Guid?>("NetworkInterfaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("network_interface_id");

                    b.Property<string>("SubnetMask")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("subnet_mask");

                    b.HasKey("Id")
                        .HasName("pk_network_element_ip_addresses");

                    b.HasIndex("IPAddress")
                        .HasDatabaseName("ix_network_element_ip_addresses_ip_address");

                    b.HasIndex("IsAvailable")
                        .HasDatabaseName("ix_network_element_ip_addresses_is_available");

                    b.HasIndex("NetworkElementId")
                        .HasDatabaseName("ix_network_element_ip_addresses_network_element_id");

                    b.ToTable("network_element_ip_addresses", (string)null);
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.NetworkInterface", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConnectedToInterfaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("connected_to_interface_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("InterfaceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("interface_type");

                    b.Property<int>("MTU")
                        .HasColumnType("integer")
                        .HasColumnName("mtu");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("mac_address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("NetworkElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("network_element_id");

                    b.Property<int>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_network_interfaces");

                    b.HasIndex("ConnectedToInterfaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_network_interfaces_connected_to_interface_id")
                        .HasFilter("connected_to_interface_id IS NOT NULL");

                    b.HasIndex("NetworkElementId")
                        .HasDatabaseName("ix_network_interfaces_network_element_id");

                    b.ToTable("network_interfaces", (string)null);
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.PONPort", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConnectedONTCount")
                        .HasColumnType("integer")
                        .HasColumnName("connected_ont_count");

                    b.Property<float>("MaxDistance")
                        .HasColumnType("real")
                        .HasColumnName("max_distance");

                    b.Property<int>("MaxONT")
                        .HasColumnType("integer")
                        .HasColumnName("max_ont");

                    b.Property<Guid>("OLTId")
                        .HasColumnType("uuid")
                        .HasColumnName("olt_id");

                    b.Property<int>("PortNumber")
                        .HasColumnType("integer")
                        .HasColumnName("port_number");

                    b.Property<string>("PortType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("port_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_pon_ports");

                    b.HasIndex("OLTId", "PortNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_pon_ports_olt_id_port_number");

                    b.ToTable("pon_ports", (string)null);
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.PerformanceMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<double?>("CriticalThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("critical_threshold");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("metric_name");

                    b.Property<string>("MetricNameAr")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("metric_name_ar");

                    b.Property<string>("ServiceId")
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<bool>("ThresholdBreached")
                        .HasColumnType("boolean")
                        .HasColumnName("threshold_breached");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.Property<double?>("WarningThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("warning_threshold");

                    b.HasKey("Id")
                        .HasName("pk_performance_metrics");

                    b.HasIndex("CollectedAt")
                        .HasDatabaseName("ix_performance_metrics_collected_at");

                    b.HasIndex("MetricName")
                        .HasDatabaseName("ix_performance_metrics_metric_name");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_performance_metrics_service_id");

                    b.HasIndex("SourceType")
                        .HasDatabaseName("ix_performance_metrics_source_type");

                    b.HasIndex("ThresholdBreached")
                        .HasDatabaseName("ix_performance_metrics_threshold_breached");

                    b.ToTable("performance_metrics", (string)null);
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.Subnet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Gateway")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("gateway");

                    b.Property<string>("Href")
                        .HasColumnType("text")
                        .HasColumnName("href");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("network");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("VLANId")
                        .HasColumnType("integer")
                        .HasColumnName("vlan_id");

                    b.HasKey("Id")
                        .HasName("pk_subnets");

                    b.HasIndex("Network")
                        .HasDatabaseName("ix_subnets_network");

                    b.HasIndex("TenantId", "Network")
                        .IsUnique()
                        .HasDatabaseName("ix_subnets_tenant_id_network");

                    b.ToTable("subnets", (string)null);
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.TopologyMap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Configuration")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_topology_maps");

                    b.ToTable("topology_maps", (string)null);
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.VLAN", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("VLANId")
                        .HasColumnType("integer")
                        .HasColumnName("vlan_id");

                    b.HasKey("Id")
                        .HasName("pk_vlans");

                    b.HasIndex("VLANId")
                        .HasDatabaseName("ix_vlans_vlan_id");

                    b.HasIndex("TenantId", "VLANId")
                        .IsUnique()
                        .HasDatabaseName("ix_vlans_tenant_id_vlan_id");

                    b.ToTable("vlans", (string)null);
                });

            modelBuilder.Entity("Obss.SharedKernel.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<string>("HandlerName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("handler_name");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_inbox_messages_received_at");

                    b.HasIndex("EventId", "HandlerName")
                        .IsUnique()
                        .HasDatabaseName("ix_inbox_messages_event_id_handler_name");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Obss.SharedKernel.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsDeadLettered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dead_lettered");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LockExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lock_expires_at");

                    b.Property<Guid?>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_created_at");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.HasIndex("ProcessedAt", "NextAttemptAt", "IsDeadLettered")
                        .HasDatabaseName("ix_outbox_messages_pending");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.OLT", b =>
                {
                    b.HasBaseType("Obss.NetworkInventory.Domain.Entities.NetworkElement");

                    b.Property<int>("MaxBandwidth")
                        .HasColumnType("integer")
                        .HasColumnName("max_bandwidth");

                    b.Property<int>("MaxONTPerPort")
                        .HasColumnType("integer")
                        .HasColumnName("max_ont_per_port");

                    b.Property<int>("MaxPONPorts")
                        .HasColumnType("integer")
                        .HasColumnName("max_pon_ports");

                    b.Property<int>("UsedPONPorts")
                        .HasColumnType("integer")
                        .HasColumnName("used_pon_ports");

                    b.HasDiscriminator().HasValue("OLT");
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.CapacityRecord", b =>
                {
                    b.HasOne("Obss.NetworkInventory.Domain.Entities.NetworkElement", null)
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_capacity_records_network_elements_element_id");
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.ConnectivityLink", b =>
                {
                    b.HasOne("Obss.NetworkInventory.Domain.Entities.NetworkElement", null)
                        .WithMany()
                        .HasForeignKey("SourceElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_connectivity_links_network_elements_source_element_id");

                    b.HasOne("Obss.NetworkInventory.Domain.Entities.NetworkElement", null)
                        .WithMany()
                        .HasForeignKey("TargetElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_connectivity_links_network_elements_target_element_id");
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.FiberCable", b =>
                {
                    b.HasOne("Obss.NetworkInventory.Domain.Entities.NetworkElement", null)
                        .WithMany()
                        .HasForeignKey("FromElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fiber_cables_network_elements_from_element_id");

                    b.HasOne("Obss.NetworkInventory.Domain.Entities.NetworkElement", null)
                        .WithMany()
                        .HasForeignKey("ToElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fiber_cables_network_elements_to_element_id");
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.NetworkElementIpAddress", b =>
                {
                    b.HasOne("Obss.NetworkInventory.Domain.Entities.NetworkElement", null)
                        .WithMany("IpAddresses")
                        .HasForeignKey("NetworkElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_network_element_ip_addresses_network_elements_network_eleme");
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.NetworkInterface", b =>
                {
                    b.HasOne("Obss.NetworkInventory.Domain.Entities.NetworkElement", null)
                        .WithMany("Interfaces")
                        .HasForeignKey("NetworkElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_network_interfaces_network_elements_network_element_id");
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.PONPort", b =>
                {
                    b.HasOne("Obss.NetworkInventory.Domain.Entities.OLT", null)
                        .WithMany("PONPorts")
                        .HasForeignKey("OLTId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pon_ports_ol_ts_olt_id");
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.NetworkElement", b =>
                {
                    b.Navigation("Interfaces");

                    b.Navigation("IpAddresses");
                });

            modelBuilder.Entity("Obss.NetworkInventory.Domain.Entities.OLT", b =>
                {
                    b.Navigation("PONPorts");
                });
#pragma warning restore 612, 618
        }
    }
}
