client obss-host {
    ipaddr = 172.28.0.0/16
    secret = obss_radius_secret
    shortname = obss-platform
    nas_type = other
}

client localhost {
    ipaddr = 127.0.0.1
    secret = obss_radius_secret
    shortname = local-dev
    nas_type = other
}
