// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Obss.ServiceCatalog.Infrastructure.Persistence;

#nullable disable

namespace Obss.ServiceCatalog.Infrastructure.Migrations
{
    [DbContext(typeof(ServiceCatalogDbContext))]
    partial class ServiceCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Obss.ServiceCatalog.Domain.Entities.ServiceCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BaseCandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_candidate_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("FeatureSpecification")
                        .HasColumnType("jsonb")
                        .HasColumnName("feature_specification");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("lifecycle_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ServiceSpecificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_specification_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_service_candidates");

                    b.HasIndex("LifecycleStatus")
                        .HasDatabaseName("ix_service_candidates_lifecycle_status");

                    b.HasIndex("ServiceSpecificationId")
                        .HasDatabaseName("ix_service_candidates_service_specification_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_service_candidates_tenant_id");

                    b.ToTable("service_candidates", (string)null);
                });

            modelBuilder.Entity("Obss.ServiceCatalog.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("lifecycle_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_service_categories");

                    b.HasIndex("LifecycleStatus")
                        .HasDatabaseName("ix_service_categories_lifecycle_status");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_service_categories_parent_category_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_service_categories_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_service_categories_tenant_id_name");

                    b.ToTable("service_categories", (string)null);
                });

            modelBuilder.Entity("Obss.ServiceCatalog.Domain.Entities.ServiceSpecCharValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacteristicId")
                        .HasColumnType("uuid")
                        .HasColumnName("characteristic_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("RangeInterval")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("range_interval");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit_of_measure");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value");

                    b.Property<string>("ValueFrom")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("value_from");

                    b.Property<string>("ValueTo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("value_to");

                    b.HasKey("Id")
                        .HasName("pk_service_spec_characteristic_values");

                    b.HasIndex("CharacteristicId")
                        .HasDatabaseName("ix_service_spec_characteristic_values_characteristic_id");

                    b.ToTable("service_spec_characteristic_values", (string)null);
                });

            modelBuilder.Entity("Obss.ServiceCatalog.Domain.Entities.ServiceSpecCharacteristic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Configurable")
                        .HasColumnType("boolean")
                        .HasColumnName("configurable");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<int?>("MaxCardinality")
                        .HasColumnType("integer")
                        .HasColumnName("max_cardinality");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("max_value");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("min_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Regex")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("regex");

                    b.Property<Guid>("ServiceSpecificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_specification_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("value_type");

                    b.HasKey("Id")
                        .HasName("pk_service_spec_characteristics");

                    b.HasIndex("ServiceSpecificationId")
                        .HasDatabaseName("ix_service_spec_characteristics_service_specification_id");

                    b.ToTable("service_spec_characteristics", (string)null);
                });

            modelBuilder.Entity("Obss.ServiceCatalog.Domain.Entities.ServiceSpecRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("relationship_type");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role");

                    b.Property<Guid>("ServiceSpecificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_specification_id");

                    b.Property<Guid>("TargetSpecificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_specification_id");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_service_spec_relationships");

                    b.HasIndex("ServiceSpecificationId")
                        .HasDatabaseName("ix_service_spec_relationships_service_specification_id");

                    b.ToTable("service_spec_relationships", (string)null);
                });

            modelBuilder.Entity("Obss.ServiceCatalog.Domain.Entities.ServiceSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsBundle")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bundle");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("lifecycle_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_service_specifications");

                    b.HasIndex("Brand")
                        .HasDatabaseName("ix_service_specifications_brand");

                    b.HasIndex("LifecycleStatus")
                        .HasDatabaseName("ix_service_specifications_lifecycle_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_service_specifications_tenant_id");

                    b.ToTable("service_specifications", (string)null);
                });

            modelBuilder.Entity("Obss.SharedKernel.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<string>("HandlerName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("handler_name");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_inbox_messages_received_at");

                    b.HasIndex("EventId", "HandlerName")
                        .IsUnique()
                        .HasDatabaseName("ix_inbox_messages_event_id_handler_name");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Obss.SharedKernel.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsDeadLettered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dead_lettered");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LockExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lock_expires_at");

                    b.Property<Guid?>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_created_at");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.HasIndex("ProcessedAt", "NextAttemptAt", "IsDeadLettered")
                        .HasDatabaseName("ix_outbox_messages_pending");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("ServiceCandidateServiceCategory", b =>
                {
                    b.Property<Guid>("CandidatesId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidates_id");

                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("categories_id");

                    b.HasKey("CandidatesId", "CategoriesId")
                        .HasName("pk_category_candidates");

                    b.HasIndex("CategoriesId")
                        .HasDatabaseName("ix_category_candidates_categories_id");

                    b.ToTable("category_candidates", (string)null);
                });

            modelBuilder.Entity("Obss.ServiceCatalog.Domain.Entities.ServiceSpecCharValue", b =>
                {
                    b.HasOne("Obss.ServiceCatalog.Domain.Entities.ServiceSpecCharacteristic", null)
                        .WithMany("Values")
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_spec_characteristic_values_service_spec_characteris");
                });

            modelBuilder.Entity("Obss.ServiceCatalog.Domain.Entities.ServiceSpecCharacteristic", b =>
                {
                    b.HasOne("Obss.ServiceCatalog.Domain.Entities.ServiceSpecification", null)
                        .WithMany("Characteristics")
                        .HasForeignKey("ServiceSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_spec_characteristics_service_specifications_service");
                });

            modelBuilder.Entity("Obss.ServiceCatalog.Domain.Entities.ServiceSpecRelationship", b =>
                {
                    b.HasOne("Obss.ServiceCatalog.Domain.Entities.ServiceSpecification", null)
                        .WithMany("Relationships")
                        .HasForeignKey("ServiceSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_spec_relationships_service_specifications_service_s");
                });

            modelBuilder.Entity("ServiceCandidateServiceCategory", b =>
                {
                    b.HasOne("Obss.ServiceCatalog.Domain.Entities.ServiceCandidate", null)
                        .WithMany()
                        .HasForeignKey("CandidatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_candidates_service_candidates_candidates_id");

                    b.HasOne("Obss.ServiceCatalog.Domain.Entities.ServiceCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_candidates_service_categories_categories_id");
                });

            modelBuilder.Entity("Obss.ServiceCatalog.Domain.Entities.ServiceSpecCharacteristic", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Obss.ServiceCatalog.Domain.Entities.ServiceSpecification", b =>
                {
                    b.Navigation("Characteristics");

                    b.Navigation("Relationships");
                });
#pragma warning restore 612, 618
        }
    }
}
