namespace Obss.Provisioning.Domain.ValueObjects;

public enum ProvisioningTaskType
{
    NetworkConfig,
    ResourceAllocation,
    DNSSetup,
    AccountSetup,
    EmailNotification,
    PhysicalInstall,
    Custom,
    FtthOntProvision,
    FtthServicePortConfig,
    FtthVlanConfig,
    FtthPppoeConfig,
    FtthActivationTest,
    FtthSlaConfig,
    FtthBackupConfig,
    AdslDslPortConfig,
    AdslLineProfileConfig,
    AdslAccessCredentials,
    LteSubscriberActivation,
    LteApnConfig,
    LtePolicyProfile,
    NumberReservation,
    NumberActivation,
    SubscriberProfileConfig,
    TelephonyFeatureConfig,
    PriTrunkConfig,
    TdmCircuitConfig,
    FreePhoneRouting,
    DedicatedServerAllocate,
    VpsAllocate,
    ColocationRackAllocate,
    WebHostingPlanSetup,
    DomainRegistration,
    AtmConnectivitySetup,
    WirelessTransmissionConfig,
    EthernetCircuitConfig,
    DiaCircuitConfig,
    StaticIpAllocation,
    WifiAccessConfig,
    QualificationCheck,
    InventoryReservation,
    RouterInterfaceConfig = 46,
    RouterBgpConfig = 47,
    RouterOspfConfig = 48,
    RouterStaticRouteConfig = 49,
    RouterSystemConfig = 50,
    RouterAclConfig = 51,
    GetRouterStatus = 52,
    GetRouterInventory = 53,
    GetRouterAlarms = 54
}
